import type { Metadata } from "next";
import { Lora } from "next/font/google";
import { Cormorant_SC } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const lora = Lora({
  subsets: ["latin"],
  variable: '--font-lora',
});

const cormorant = Cormorant_SC({
  subsets: ["latin"],
  variable: '--font-cormorant',
  weight: "300"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lora.variable} ${cormorant.variable}`}>
      <body>{children}</body>
    </html>
  );
}
